In [1]:
import numpy as np
a = np.ones([506 ,1])
b = np.eye(506)
np.shape(b)

(506, 506)

In [2]:
np.c_[a , b]

array([[1., 1., 0., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 0., 1.]])

In [14]:
np.hstack((a ,b))

array([[1., 1., 0., ..., 0., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 0., 1.]])

In [13]:
c = np.array([[1,2,3] ,[3,4,5]])
np.shape(c)

(2, 3)

In [17]:
X = np.ones([506 , 13])
np.zeros(np.size(X , axis = 1))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])