# NumPy

Numpy is a python library primarily used for fast array manipulations. It has inbuilt methods for various linear algebra functions that we will be needing throughtout the course. 

The speed of NumPy is primarily because the array data structure of Numpy, `numpy.ndarray` or 'N dimensional array', are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently. These arrays are approximately 50x faster than traditional lists in pyhton

> Note: Whenever Array is used in this notebook, we mean an ndarray



# Installation Instructions
Anaconda normally comes with libraries like numpy, pandas, matplotlib, etc pre installed.

In case you are running a miniconda install, or don't have numpy installed you can do it as follows: in your desired conda virtual environment, run the following command on your terminal

```
conda install numpy
```

or the following on your jupyter notebook:
```
!conda install numpy
```

In [0]:
import numpy as np

## Axes of a matrix

In numpy, the dimensions are called axes.

For example,

- Array with 1 axis that has 3 elements (ie length 3)
```
[1.0, 2.0, 13.73]
```

- Array with 2 dimensions of length 2 and 3 respectively:
```
[[ 1., 0., 0.], 
[ 0., 1., 2.]]
```

## Basics of NumPy Array

The Multidimesnional array in numpy is a table with the following commonly used properties


In [0]:
arr = np.array(
    [[ 1., 0., 0.], 
     [ 0., 1., 2.]]
)

print(f"Type: {type(arr)}")
print(f"Dimesnions: {arr.ndim}")
print(f"Shape: {arr.shape}") # Returns tuple (r, c), for matrix with r rows and c columms
print(f"Type: {arr.dtype}")
print(f"Size: {arr.size}") # Returns total number of elements in array

Type: <class 'numpy.ndarray'>
Dimesnions: 2
Shape: (2, 3)
Type: float64
Size: 6


## Array Creation

There are various methods for creating numpy Arrays:

In [0]:
# Creating from list
arr = np.array([2., 3., 4.])
print(arr)

[2. 3. 4.]


In [0]:
# Array of integers in a given range
print(np.arange(10))
print(np.arange(start=5, stop=20, step=5))

[0 1 2 3 4 5 6 7 8 9]
[ 5 10 15]


In [0]:
# Empty Array of given shape
print(np.empty((4, 3))) # Creates an array of garbage values with given shape

[[2.95311495e-316 0.00000000e+000 4.27366784e-321]
 [2.01294834e-316 6.92722490e-310 6.92722490e-310]
 [6.92722490e-310 6.92722490e-310 2.95311495e-316]
 [4.94065646e-324 1.90979621e-313 0.00000000e+000]]


In [0]:
print(np.zeros((2, 5))) # Array of Zeros
print(np.ones((2, 4))) # Array of Ones

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [0]:
# Identity matrix
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [0]:
# Diagonal Arry
print(np.diag([2, 3, 5]))

[[2 0 0]
 [0 3 0]
 [0 0 5]]


In [0]:
# Randomly Initialized arrays:
print(np.random.rand(2, 3), end='\n\n') # Array of given shape, with uniform sample over [0,1)
print(np.random.uniform(-1, 1, 5), end='\n\n') # Array of size 5, with uniform sample over (-1, 1)
print(np.random.randn(3, 1), end='\n\n') # Array of shape (3, 1) with standard normal sample

[[0.81735212 0.675865   0.38725118]
 [0.62905501 0.78678513 0.16011976]]

[-0.47665861  0.07952054 -0.60297088 -0.34510386  0.98753692]

[[-0.63702399]
 [-1.53344392]
 [ 0.24684941]]



## Indexing, Slicing, Iterating





### One dimensional Arrays
Indexing, Slicing, Iterating is much like the operations on lists

In [0]:
a = np.arange(10) ** 2 # Numpy array containinng first 10 squares

print(a, end='\n\n')
print(a[2], end='\n\n') # Index based Selection
print(a[3:8], end='\n\n') # Range based Selection

a[:6:2] = -10
print(a, end='\n\n')

print(a[::-1], end='\n\n') # Reversed List

[ 0  1  4  9 16 25 36 49 64 81]

4

[ 9 16 25 36 49]

[-10   1 -10   9 -10  25  36  49  64  81]

[ 81  64  49  36  25 -10   9 -10   1 -10]



### Multidimensional Arrays

These arrays have one index per axis, given in a tuple, separated by commas:

In [0]:
arr = np.arange(24).reshape(3, 8)

print(arr, end='\n\n')

print(arr[2, 2], end='\n\n')

print(arr[2], end='\n\n') # is the same as arr[2, :], and arr[2, 0:8]

print(arr[1:3, -1]) # Last column of rows indexed 1, 2

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]

18

[16 17 18 19 20 21 22 23]

[15 23]


## Shape Manipulation

An array has a shape determine by the length of each axis.


In [0]:
arr = np.random.randn(3, 4)
print(arr)
print(f"Shape: {arr.shape}")

[[-0.93596265  0.35834686  0.22090765 -1.81324082]
 [ 0.81597095  0.2005792   0.90400042  0.19316658]
 [ 0.31328302 -0.70835043 -1.17410895 -1.29044735]]
Shape: (3, 4)


In [0]:
print(arr.ravel()) # ndarray.ravel() Flattens the array

[-0.93596265  0.35834686  0.22090765 -1.81324082  0.81597095  0.2005792
  0.90400042  0.19316658  0.31328302 -0.70835043 -1.17410895 -1.29044735]


In [0]:
print(arr.T) # Transpose of the array

[[-0.93596265  0.81597095  0.31328302]
 [ 0.35834686  0.2005792  -0.70835043]
 [ 0.22090765  0.90400042 -1.17410895]
 [-1.81324082  0.19316658 -1.29044735]]


In [0]:
print(arr.reshape(2, 6), end="\n\n") # Returns reshaped array with given shape

# The argument of -1 is used to automatically calculate the dimension according 
# to the size of the array
arr_mod = arr.reshape(1, -1)
print(arr_mod)
print(arr_mod.shape)

[[-0.93596265  0.35834686  0.22090765 -1.81324082  0.81597095  0.2005792 ]
 [ 0.90400042  0.19316658  0.31328302 -0.70835043 -1.17410895 -1.29044735]]

[[-0.93596265  0.35834686  0.22090765 -1.81324082  0.81597095  0.2005792
   0.90400042  0.19316658  0.31328302 -0.70835043 -1.17410895 -1.29044735]]
(1, 12)


## Views and Copies
When operating and manipulating arrays, their data is sometimes copied into a new array and sometimes not. There are three cases:




### 1. No Copy at all
- Simple assignments does not create copies of the ndarray object

In [0]:
a = np.arange(5)
print(a)

b = a 
print(b is a)

[0 1 2 3 4]
True


- Python passes mutable objects as references, so function calls make no copy.

> Mutable objects are those which can be modified after creating, whereas immutable objects can't.
> For example, a list is a mutable object whereas a tuple is immutable

In [0]:
def f(x):
    return x

b = f(a)
print(f"a: {id(a)}")
print(f"b: {id(b)}")


a: 140208935376976
b: 140208935376976


### 2. Shallow Copy or View
Different array objects can share the same data. -
The view method creates a new array object that looks at the same data. This means that, modifying one, changes the other as well. 

In [0]:
c = a.view()
print(c is a)

False


In [0]:
c[3] = 16
print(a)

[ 0  1  2 16  4]


- Slicing an array returns a view of *it*

In [0]:
s = a[:3]
s[2] = 9
print(a)

[ 0  1  9 16  4]


### 3. Deep Copy
The copy method makes a complete copy of the array and its data. This means that modifying one has no effect on the other.

Note: Call `copy` after slicing, if original array is not required anymore

In [0]:
d = a.copy()

print(d is a)

False


In [0]:
d[0] = 99
print(a)
print(d)

[ 0  1  9 16  4]
[99  1  9 16  4]


## Mathematics on Arrays

Various Mathematical Functions have efficient implementations in NumPy

### 1. Basic Operations

Operations such as addition among arrays using `+`, multiplication of two arrays `*`, division with a scalar using `/`, exponentiation with a scalar are performed element wise. 

In [0]:
a = np.arange(9).reshape(3, -1)
b = np.arange(10, 19).reshape(3, -1)

print(a)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [0]:
a * b

array([[  0,  11,  24],
       [ 39,  56,  75],
       [ 96, 119, 144]])

In [0]:
a ** 3

array([[  0,   1,   8],
       [ 27,  64, 125],
       [216, 343, 512]])

### 2. Sum of Arrays
Used to find the sum of elements

In [0]:
arr = np.arange(24).reshape(4, -1)
print(arr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [0]:
# Sum of all elements in the array
print(arr.sum())

276


Sum can be used to calculate sums of the axes

In [0]:
print(arr.sum(axis=0)) # Sum of axis 0, ie row
print(arr.sum(axis=1)) # Sum of axis 1, ie columns

[36 40 44 48 52 56]
[ 15  51  87 123]


### 3. Universal Functions
Functions like log, exp, sqrt, etc are defined in the library to calculate them for all the elements efficiently


In [0]:
print(np.exp(arr)) # Used to calculate exponential of the elements

[[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
  5.45981500e+01 1.48413159e+02]
 [4.03428793e+02 1.09663316e+03 2.98095799e+03 8.10308393e+03
  2.20264658e+04 5.98741417e+04]
 [1.62754791e+05 4.42413392e+05 1.20260428e+06 3.26901737e+06
  8.88611052e+06 2.41549528e+07]
 [6.56599691e+07 1.78482301e+08 4.85165195e+08 1.31881573e+09
  3.58491285e+09 9.74480345e+09]]


### 4. The Dot Product
The Dot product is also a universal function, but with a few caveats. 

Note: It is behaves like matrix multiplication for multidimensional arrays

In [0]:
a = np.arange(6).reshape(2, 3)
b = np.arange(12).reshape(3, 4)

print(a)
print(b)

[[0 1 2]
 [3 4 5]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [0]:
print(np.dot(a, b))

[[20 23 26 29]
 [56 68 80 92]]


In [0]:
print(a.dot(b))

[[20 23 26 29]
 [56 68 80 92]]


In [0]:
print(a @ b)

[[20 23 26 29]
 [56 68 80 92]]


For x1 @ x2 to make sense for multidimensional arrays, we require that:

**length of axis 1 of x1 == length of axis 0 of x2**

Otherwise, the following error is thrown:

In [0]:
print(np.dot(b, a))

ValueError: ignored

In [0]:
print(b @ a)

ValueError: ignored